//! C backend: plain `struct`s over the shared ABI, emitted as a header.

use super::symbol;
use crate::ir::*;

/// Generate a single self-contained C header for the whole program.
pub fn generate(program: &Program) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    for msg in &program.messages {
        out.push('\n');
        emit_message(&mut out, msg);
    }
    out.push_str("\n#endif  // ROSCMP_GENERATED_H\n");
    out
}

const HEADER: &str = "\
/* Generated by roscmp. Do not edit. */
#ifndef ROSCMP_GENERATED_H
#define ROSCMP_GENERATED_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/* ABI of a ROS string / sequence: owning pointer + length + capacity. */
typedef struct roscmp_string {
  char* data;
  size_t size;
  size_t capacity;
} roscmp_string;

typedef struct roscmp_sequence {
  void* data;
  size_t size;
  size_t capacity;
} roscmp_sequence;

/* Owned byte buffer returned by *_serialize; release with roscmp_buf_free. */
typedef struct RoscmpBuf {
  uint8_t* ptr;
  size_t len;
  size_t cap;
} RoscmpBuf;

void roscmp_buf_free(RoscmpBuf buf);
";

fn emit_message(out: &mut String, msg: &Message) {
    let name = symbol(&msg.id);

    for c in &msg.constants {
        // `enum`-style integer constants stay typed via macros; emit as #define.
        out.push_str(&format!(
            "#define {}__{} {}\n",
            name,
            c.name,
            render_value(&c.value)
        ));
    }

    out.push_str(&format!("typedef struct {name} {{\n"));
    for f in &msg.fields {
        let (ty, suffix) = render_field(&f.ty);
        out.push_str(&format!("  {} {}{};\n", ty, f.name, suffix));
    }
    out.push_str(&format!("}} {name};\n"));

    // FFI prototypes: serialize/deserialize/fini implemented in the Rust lib.
    out.push_str(&format!(
        "RoscmpBuf roscmp_{name}_serialize(const {name}* msg, uint8_t endian);\n\
         int roscmp_{name}_deserialize(const uint8_t* buf, size_t len, {name}* out);\n\
         void roscmp_{name}_fini({name}* msg);\n"
    ));
}

/// Returns (type spelling, declarator suffix) — C puts array dims after the name.
fn render_field(ty: &ResolvedType) -> (String, String) {
    match ty {
        ResolvedType::Scalar(e) => (render_element(e), String::new()),
        ResolvedType::Array { elem, len } => (render_element(elem), format!("[{len}]")),
        ResolvedType::Sequence { .. } => ("roscmp_sequence".to_string(), String::new()),
    }
}

fn render_element(e: &Element) -> String {
    match e {
        Element::Prim(p) => p.c().to_string(),
        Element::String { .. } => "roscmp_string".to_string(),
        Element::Message(id) => symbol(id),
    }
}

fn render_value(v: &crate::ast::Value) -> String {
    use crate::ast::Value;
    match v {
        Value::Bool(b) => if *b { "1" } else { "0" }.to_string(),
        Value::Integer(i) => i.to_string(),
        Value::Float(f) => format!("{f:?}"),
        Value::String(s) => format!("{s:?}"),
        Value::Array(_) => "/* array constant unsupported */".to_string(),
    }
}
