//! Python backend: `ctypes.Structure` subclasses over the shared ABI.

use super::symbol;
use crate::ir::*;

/// Generate a single self-contained Python module for the whole program.
pub fn generate(program: &Program) -> String {
    let mut out = String::new();
    out.push_str(HEADER);
    for msg in &program.messages {
        out.push('\n');
        emit_message(&mut out, msg);
    }
    emit_ffi(&mut out, program);
    out
}

/// Emit the loader + per-message serialize/deserialize helpers that call into
/// the compiled Rust shared library (the single CDR serializer).
fn emit_ffi(out: &mut String, program: &Program) {
    out.push_str(
        "\n\n_lib = None\n\n\n\
         class RoswellBuf(ctypes.Structure):\n\
         \x20   _fields_ = [\n\
         \x20       (\"ptr\", ctypes.POINTER(ctypes.c_uint8)),\n\
         \x20       (\"len\", ctypes.c_size_t),\n\
         \x20       (\"cap\", ctypes.c_size_t),\n\
         \x20   ]\n\n\n\
         def load(path):\n\
         \x20   \"\"\"Load the roswell-generated shared library and bind its symbols.\"\"\"\n\
         \x20   global _lib\n\
         \x20   _lib = ctypes.CDLL(path)\n\
         \x20   _lib.roswell_buf_free.argtypes = [RoswellBuf]\n\
         \x20   _lib.roswell_buf_free.restype = None\n",
    );
    for msg in &program.messages {
        let name = symbol(&msg.id);
        out.push_str(&format!(
            "    _lib.roswell_{name}_serialize.argtypes = [ctypes.POINTER({name}), ctypes.c_uint8]\n\
             \x20   _lib.roswell_{name}_serialize.restype = RoswellBuf\n\
             \x20   _lib.roswell_{name}_deserialize.argtypes = [ctypes.POINTER(ctypes.c_uint8), ctypes.c_size_t, ctypes.POINTER({name})]\n\
             \x20   _lib.roswell_{name}_deserialize.restype = ctypes.c_int\n\
             \x20   _lib.roswell_{name}_fini.argtypes = [ctypes.POINTER({name})]\n\
             \x20   _lib.roswell_{name}_fini.restype = None\n"
        ));
    }
    out.push_str("    return _lib\n");

    for msg in &program.messages {
        let name = symbol(&msg.id);
        out.push_str(&format!(
            "\n\ndef {name}_serialize(msg, endian=0):\n\
             \x20   buf = _lib.roswell_{name}_serialize(ctypes.byref(msg), endian)\n\
             \x20   data = ctypes.string_at(buf.ptr, buf.len)\n\
             \x20   _lib.roswell_buf_free(buf)\n\
             \x20   return data\n\n\n\
             def {name}_deserialize(data):\n\
             \x20   out = {name}()\n\
             \x20   arr = (ctypes.c_uint8 * len(data)).from_buffer_copy(data)\n\
             \x20   rc = _lib.roswell_{name}_deserialize(arr, len(data), ctypes.byref(out))\n\
             \x20   if rc != 0:\n\
             \x20       raise ValueError(\"CDR deserialize failed\")\n\
             \x20   return out\n"
        ));
    }
}

const HEADER: &str = "\
# Generated by roswell. Do not edit.
import ctypes


class RosString(ctypes.Structure):
    _fields_ = [
        (\"data\", ctypes.c_char_p),
        (\"size\", ctypes.c_size_t),
        (\"capacity\", ctypes.c_size_t),
    ]


class RosSequence(ctypes.Structure):
    _fields_ = [
        (\"data\", ctypes.c_void_p),
        (\"size\", ctypes.c_size_t),
        (\"capacity\", ctypes.c_size_t),
    ]
";

fn emit_message(out: &mut String, msg: &Message) {
    let name = symbol(&msg.id);

    out.push_str(&format!("\nclass {name}(ctypes.Structure):\n"));
    if msg.fields.is_empty() {
        out.push_str("    _fields_ = []\n");
    } else {
        out.push_str("    _fields_ = [\n");
        for f in &msg.fields {
            out.push_str(&format!(
                "        (\"{}\", {}),\n",
                f.name,
                render_type(&f.ty)
            ));
        }
        out.push_str("    ]\n");
    }

    // Constants live as class attributes (set after the layout is defined).
    for c in &msg.constants {
        out.push_str(&format!(
            "{}.{} = {}\n",
            name,
            c.name,
            render_value(&c.value)
        ));
    }
}

fn render_type(ty: &ResolvedType) -> String {
    match ty {
        ResolvedType::Scalar(e) => render_element(e),
        ResolvedType::Array { elem, len } => format!("{} * {}", render_element(elem), len),
        ResolvedType::Sequence { .. } => "RosSequence".to_string(),
    }
}

fn render_element(e: &Element) -> String {
    match e {
        Element::Prim(p) => p.ctypes().to_string(),
        Element::String { .. } => "RosString".to_string(),
        Element::Message(id) => symbol(id),
    }
}

fn render_value(v: &crate::ast::Value) -> String {
    use crate::ast::Value;
    match v {
        Value::Bool(b) => if *b { "True" } else { "False" }.to_string(),
        Value::Integer(i) => i.to_string(),
        Value::Float(f) => format!("{f:?}"),
        Value::String(s) => format!("{s:?}"),
        Value::Array(_) => "None  # array constant unsupported".to_string(),
    }
}
