//! Rust backend: `#[repr(C)]` structs over the shared ABI, plus generated CDR
//! serialize/deserialize and an owning `fini` for each message.

use super::symbol;
use crate::ir::*;

/// The CDR runtime, embedded so generated files are self-contained.
const CDR_RUNTIME: &str = include_str!("../cdr_runtime.rs");

/// Generate a single self-contained Rust source file for the whole program.
pub fn generate(program: &Program) -> String {
    let mut out = String::new();
    out.push_str(PREAMBLE);
    out.push_str(CDR_RUNTIME);
    out.push_str(ROS_TYPES);
    out.push_str(FFI_RUNTIME);
    for msg in &program.messages {
        out.push('\n');
        let hash = crate::typehash::type_hash(&program.messages, &msg.id);
        emit_message(&mut out, msg, hash.as_deref());
    }
    out
}

const PREAMBLE: &str = "\
// Generated by roscmp. Do not edit.
#![allow(non_camel_case_types, non_upper_case_globals, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]
use core::ffi::c_char;

";

/// `RosString`/`RosSequence` definitions and their owning helpers. These ride
/// the same `{ data, size, capacity }` ABI used by the C and Python backends.
const ROS_TYPES: &str = "
/// ABI of a ROS string: NUL-terminated, owning pointer + length + capacity.
#[repr(C)]
pub struct RosString {
    pub data: *mut c_char,
    pub size: usize,
    pub capacity: usize,
}

impl RosString {
    /// # Safety
    /// `data` must point to `size` valid UTF-8 bytes.
    pub unsafe fn as_str(&self) -> &str {
        if self.data.is_null() || self.size == 0 {
            return \"\";
        }
        let bytes = core::slice::from_raw_parts(self.data as *const u8, self.size);
        core::str::from_utf8_unchecked(bytes)
    }

    /// Allocate an owning, NUL-terminated copy of `s`.
    pub fn alloc(s: &str) -> Self {
        let mut bytes = s.as_bytes().to_vec();
        bytes.push(0);
        let mut bytes = core::mem::ManuallyDrop::new(bytes);
        RosString {
            data: bytes.as_mut_ptr() as *mut c_char,
            size: bytes.len() - 1,
            capacity: bytes.capacity(),
        }
    }

    /// # Safety
    /// Frees the owned buffer; call at most once. Idempotent on null.
    pub unsafe fn free(&mut self) {
        if !self.data.is_null() {
            drop(Vec::from_raw_parts(self.data as *mut u8, self.capacity, self.capacity));
            self.data = core::ptr::null_mut();
            self.size = 0;
            self.capacity = 0;
        }
    }
}

/// ABI of a ROS sequence: owning pointer + length + capacity.
#[repr(C)]
pub struct RosSequence<T> {
    pub data: *mut T,
    pub size: usize,
    pub capacity: usize,
}

impl<T> RosSequence<T> {
    /// # Safety
    /// `data` must point to `size` valid `T` values.
    pub unsafe fn as_slice(&self) -> &[T] {
        if self.data.is_null() {
            return &[];
        }
        core::slice::from_raw_parts(self.data, self.size)
    }

    /// Take ownership of `v`'s buffer.
    pub fn alloc(v: Vec<T>) -> Self {
        let mut v = core::mem::ManuallyDrop::new(v);
        RosSequence {
            data: v.as_mut_ptr(),
            size: v.len(),
            capacity: v.capacity(),
        }
    }

    /// # Safety
    /// Reconstitutes the owning `Vec`; call at most once.
    pub unsafe fn into_vec(self) -> Vec<T> {
        Vec::from_raw_parts(self.data, self.size, self.capacity)
    }
}
";

/// The C-ABI buffer type returned by `*_serialize`, freed by `roscmp_buf_free`.
/// This is the only allocation handoff between Rust and the other languages.
const FFI_RUNTIME: &str = "
/// Owned byte buffer returned across the FFI boundary.
#[repr(C)]
pub struct RoscmpBuf {
    pub ptr: *mut u8,
    pub len: usize,
    pub cap: usize,
}

/// Free a buffer produced by a `*_serialize` call.
#[no_mangle]
pub extern \"C\" fn roscmp_buf_free(buf: RoscmpBuf) {
    if !buf.ptr.is_null() {
        unsafe { drop(Vec::from_raw_parts(buf.ptr, buf.len, buf.cap)); }
    }
}
";

fn emit_message(out: &mut String, msg: &Message, type_hash: Option<&str>) {
    let name = symbol(&msg.id);

    if let Some(hash) = type_hash {
        out.push_str(&format!(
            "/// RIHS01 type hash (matches ROS2 discovery).\npub const {name}__TYPE_HASH: &str = {hash:?};\n"
        ));
    }

    for c in &msg.constants {
        let ty = match &c.prim {
            ConstType::Prim(p) => p.rust(),
            ConstType::String => "&str",
        };
        out.push_str(&format!(
            "pub const {}__{}: {} = {};\n",
            name,
            c.name,
            ty,
            render_value(&c.value, &c.prim)
        ));
    }

    out.push_str("#[repr(C)]\n");
    out.push_str(&format!("pub struct {name} {{\n"));
    for f in &msg.fields {
        out.push_str(&format!("    pub {}: {},\n", f.name, render_type(&f.ty)));
    }
    out.push_str("}\n");

    emit_cdr(out, msg, &name);
    emit_ffi(out, &name);
}

/// Emit `extern "C"` wrappers so C and Python serialize through this one Rust
/// implementation rather than reimplementing CDR.
fn emit_ffi(out: &mut String, name: &str) {
    out.push_str(&format!(
        "
#[no_mangle]
pub extern \"C\" fn roscmp_{name}_serialize(msg: *const {name}, endian: u8) -> RoscmpBuf {{
    if msg.is_null() {{ return RoscmpBuf {{ ptr: core::ptr::null_mut(), len: 0, cap: 0 }}; }}
    let e = if endian == 0 {{ Endian::Little }} else {{ Endian::Big }};
    let v = unsafe {{ (*msg).to_cdr(e) }};
    let mut v = core::mem::ManuallyDrop::new(v);
    RoscmpBuf {{ ptr: v.as_mut_ptr(), len: v.len(), cap: v.capacity() }}
}}

#[no_mangle]
pub extern \"C\" fn roscmp_{name}_deserialize(buf: *const u8, len: usize, out: *mut {name}) -> i32 {{
    if buf.is_null() || out.is_null() {{ return -1; }}
    let slice = unsafe {{ core::slice::from_raw_parts(buf, len) }};
    match {name}::from_cdr(slice) {{
        Ok(m) => {{ unsafe {{ core::ptr::write(out, m); }} 0 }}
        Err(_) => -1,
    }}
}}

#[no_mangle]
pub extern \"C\" fn roscmp_{name}_fini(msg: *mut {name}) {{
    if !msg.is_null() {{ unsafe {{ (*msg).fini(); }} }}
}}
"
    ));
}

/// Emit `to_cdr`/`serialize_into`/`from_cdr`/`deserialize_from`/`fini`.
fn emit_cdr(out: &mut String, msg: &Message, name: &str) {
    out.push_str(&format!("\nimpl {name} {{\n"));

    out.push_str(
        "    pub fn to_cdr(&self, endian: Endian) -> Vec<u8> {\n\
         \x20       let mut w = Writer::new(endian);\n\
         \x20       unsafe { self.serialize_into(&mut w); }\n\
         \x20       w.finish()\n\
         \x20   }\n\n",
    );

    out.push_str("    /// # Safety\n    /// Reads owning pointers in strings/sequences; they must be valid.\n");
    out.push_str("    pub unsafe fn serialize_into(&self, w: &mut Writer) {\n");
    for f in &msg.fields {
        out.push_str(&ser_field(f));
    }
    out.push_str("    }\n\n");

    out.push_str(
        "    pub fn from_cdr(buf: &[u8]) -> Result<Self, CdrError> {\n\
         \x20       let mut r = Reader::new(buf)?;\n\
         \x20       Self::deserialize_from(&mut r)\n\
         \x20   }\n\n",
    );

    out.push_str("    pub fn deserialize_from(r: &mut Reader) -> Result<Self, CdrError> {\n");
    out.push_str("        Ok(Self {\n");
    for f in &msg.fields {
        out.push_str(&format!("            {}: {},\n", f.name, de_field(f)));
    }
    out.push_str("        })\n    }\n\n");

    out.push_str(
        "    /// # Safety\n    /// Frees owned buffers; call at most once per owned message.\n",
    );
    out.push_str("    pub unsafe fn fini(&mut self) {\n");
    for f in &msg.fields {
        out.push_str(&fini_field(f));
    }
    out.push_str("    }\n");

    out.push_str("}\n");
}

// ---- serialize ----------------------------------------------------------

fn ser_field(f: &ResolvedField) -> String {
    let name = &f.name;
    match &f.ty {
        ResolvedType::Scalar(e) => format!("        {}\n", ser_scalar(e, name)),
        ResolvedType::Array { elem, .. } => format!(
            "        for __e in &self.{name} {{ {} }}\n",
            ser_elem_ref(elem)
        ),
        ResolvedType::Sequence { elem, .. } => format!(
            "        w.write_seq_len(self.{name}.size);\n        for __e in self.{name}.as_slice() {{ {} }}\n",
            ser_elem_ref(elem)
        ),
    }
}

/// Serialize a scalar field accessed as `self.<name>`.
fn ser_scalar(e: &Element, name: &str) -> String {
    match e {
        Element::Prim(p) => format!("w.write_{}(self.{name});", p.cdr_fn()),
        Element::String { .. } => format!("w.write_string(self.{name}.as_str());"),
        Element::Message(_) => format!("self.{name}.serialize_into(w);"),
    }
}

/// Serialize an element referenced by the loop variable `__e` (a `&Element`).
fn ser_elem_ref(e: &Element) -> String {
    match e {
        Element::Prim(p) => format!("w.write_{}(*__e);", p.cdr_fn()),
        Element::String { .. } => "w.write_string(__e.as_str());".to_string(),
        Element::Message(_) => "__e.serialize_into(w);".to_string(),
    }
}

// ---- deserialize --------------------------------------------------------

fn de_field(f: &ResolvedField) -> String {
    match &f.ty {
        ResolvedType::Scalar(e) => de_elem(e),
        ResolvedType::Array { elem, len } => format!(
            "{{ let mut __t = Vec::with_capacity({len}); for _ in 0..{len} {{ __t.push({}); }} \
             match __t.try_into() {{ Ok(__a) => __a, Err(_) => return Err(CdrError::Truncated) }} }}",
            de_elem(elem)
        ),
        ResolvedType::Sequence { elem, .. } => format!(
            "{{ let __n = r.read_seq_len()?; let mut __v = Vec::with_capacity(__n); \
             for _ in 0..__n {{ __v.push({}); }} RosSequence::alloc(__v) }}",
            de_elem(elem)
        ),
    }
}

/// Read one element value.
fn de_elem(e: &Element) -> String {
    match e {
        Element::Prim(p) => format!("r.read_{}()?", p.cdr_fn()),
        Element::String { .. } => "RosString::alloc(&r.read_string()?)".to_string(),
        Element::Message(id) => format!("{}::deserialize_from(r)?", symbol(id)),
    }
}

// ---- fini ---------------------------------------------------------------

fn fini_field(f: &ResolvedField) -> String {
    let name = &f.name;
    match &f.ty {
        ResolvedType::Scalar(e) => match fini_elem(e, &format!("self.{name}")) {
            Some(stmt) => format!("        {stmt}\n"),
            None => String::new(),
        },
        ResolvedType::Array { elem, .. } => match fini_elem(elem, "__e") {
            Some(stmt) => format!("        for __e in &mut self.{name} {{ {stmt} }}\n"),
            None => String::new(),
        },
        ResolvedType::Sequence { elem, .. } => {
            let inner = match fini_elem(elem, "__e") {
                Some(stmt) => format!("for __e in &mut __v {{ {stmt} }} "),
                None => String::new(),
            };
            format!(
                "        {{ let mut __v = core::mem::replace(&mut self.{name}, RosSequence::alloc(Vec::new())).into_vec(); {inner}drop(__v); }}\n"
            )
        }
    }
}

/// The statement to free element `var` (a `&mut Element`), or `None` if the
/// element owns nothing.
fn fini_elem(e: &Element, var: &str) -> Option<String> {
    match e {
        Element::Prim(_) => None,
        Element::String { .. } => Some(format!("{var}.free();")),
        Element::Message(_) => Some(format!("{var}.fini();")),
    }
}

// ---- shared -------------------------------------------------------------

fn render_type(ty: &ResolvedType) -> String {
    match ty {
        ResolvedType::Scalar(e) => render_element(e),
        ResolvedType::Array { elem, len } => format!("[{}; {}]", render_element(elem), len),
        ResolvedType::Sequence { elem, .. } => format!("RosSequence<{}>", render_element(elem)),
    }
}

fn render_element(e: &Element) -> String {
    match e {
        Element::Prim(p) => p.rust().to_string(),
        Element::String { .. } => "RosString".to_string(),
        Element::Message(id) => symbol(id),
    }
}

fn render_value(v: &crate::ast::Value, ty: &ConstType) -> String {
    use crate::ast::Value;
    match v {
        Value::Bool(b) => b.to_string(),
        // Suffix integer literals with the declared width (e.g. `123u8`).
        Value::Integer(i) => match ty {
            ConstType::Prim(p) => format!("{i}{}", p.rust()),
            ConstType::String => i.to_string(),
        },
        Value::Float(f) => format!("{f:?}"),
        Value::String(s) => format!("{s:?}"),
        Value::Array(_) => "/* array constant unsupported */".to_string(),
    }
}
