//! Rust no_std backend: heapless message structs (fixed-capacity strings and
//! sequences, no `RosString`/`RosSequence` triples, no FFI wrappers) with CDR
//! encode/decode over caller-provided `&mut [u8]` buffers — `core` only, no
//! `alloc`, no panics. For values that fit their capacities, the emitted bytes
//! are byte-identical to the std backend's (`tests/nostd_codegen_tests.rs`
//! pins this).

use super::rust::{field_ident, render_value};
use super::symbol;
use crate::ir::*;

/// The no_std CDR runtime, embedded so generated files are self-contained.
const CDR_RUNTIME: &str = include_str!("../cdr_runtime_nostd.rs");

/// Default capacities for fields whose `.msg` type carries no bound.
/// A declared bound (`string<=N`, `T[<=N]`) always wins over these.
#[derive(Debug, Clone, Copy)]
pub struct Caps {
    /// Capacity in bytes of an unbounded `string` field.
    pub string: usize,
    /// Capacity in elements of an unbounded sequence field.
    pub seq: usize,
}

impl Default for Caps {
    fn default() -> Self {
        Caps {
            string: 64,
            seq: 16,
        }
    }
}

const PREAMBLE: &str = "\
// Generated by roscmp (--no-std). Do not edit.
//
// core-only: no std, no alloc, no heap. Encode into caller-provided buffers;
// every fallible operation returns `Result` (no panics, no silent truncation).
#![allow(non_camel_case_types, non_upper_case_globals, dead_code, clippy::all, clippy::pedantic, clippy::nursery)]

";

/// Generate a single self-contained, `core`-only Rust source file.
pub fn generate(program: &Program, caps: Caps) -> String {
    let mut out = String::new();
    out.push_str(PREAMBLE);
    out.push_str(CDR_RUNTIME);
    for msg in &program.messages {
        out.push('\n');
        let hash = crate::typehash::type_hash(&program.messages, &msg.id);
        emit_message(&mut out, msg, hash.as_deref(), caps);
    }
    out
}

fn emit_message(out: &mut String, msg: &Message, type_hash: Option<&str>, caps: Caps) {
    let name = symbol(&msg.id);

    if let Some(hash) = type_hash {
        out.push_str(&format!(
            "/// RIHS01 type hash (matches ROS2 discovery).\npub const {name}__TYPE_HASH: &str = {hash:?};\n"
        ));
    }

    for c in &msg.constants {
        let ty = match &c.prim {
            ConstType::Prim(p) => p.rust(),
            ConstType::String => "&str",
        };
        out.push_str(&format!(
            "pub const {}__{}: {} = {};\n",
            name,
            c.name,
            ty,
            render_value(&c.value, &c.prim)
        ));
    }

    out.push_str(&format!("pub struct {name} {{\n"));
    for f in &msg.fields {
        out.push_str(&format!(
            "    pub {}: {},\n",
            field_ident(&f.name),
            render_type(&f.ty, caps)
        ));
    }
    out.push_str("}\n");

    emit_default(out, msg, &name, caps);
    emit_cdr(out, msg, &name, caps);
}

/// Manual `Default` (derive fails on `[f64; N]` for `N > 32`); needed so
/// `BoundedVec<Msg, N>` and array decoding can build placeholder elements.
fn emit_default(out: &mut String, msg: &Message, name: &str, caps: Caps) {
    out.push_str(&format!(
        "\nimpl Default for {name} {{\n    fn default() -> Self {{\n        Self {{\n"
    ));
    for f in &msg.fields {
        out.push_str(&format!(
            "            {}: {},\n",
            field_ident(&f.name),
            default_expr(&f.ty, caps)
        ));
    }
    out.push_str("        }\n    }\n}\n");
}

fn default_expr(ty: &ResolvedType, caps: Caps) -> String {
    match ty {
        ResolvedType::Scalar(e) => elem_default(e, caps),
        ResolvedType::Array { elem, .. } => {
            format!("core::array::from_fn(|_| {})", elem_default(elem, caps))
        }
        ResolvedType::Sequence { .. } => "BoundedVec::new()".to_string(),
    }
}

fn elem_default(e: &Element, caps: Caps) -> String {
    match e {
        Element::Prim(p) => match p {
            Prim::Bool => "false".to_string(),
            Prim::Float32 => "0.0f32".to_string(),
            Prim::Float64 => "0.0f64".to_string(),
            _ => format!("0{}", p.rust()),
        },
        Element::String { bound, .. } => {
            format!("BoundedString::<{}>::new()", bound.unwrap_or(caps.string))
        }
        Element::Message(id) => format!("{}::default()", symbol(id)),
    }
}

/// Emit `to_cdr`/`to_cdr_xcdr2`/`serialize_into`/`from_cdr`/`deserialize_from`.
/// No `fini`: nothing owns heap memory.
fn emit_cdr(out: &mut String, msg: &Message, name: &str, caps: Caps) {
    out.push_str(&format!("\nimpl {name} {{\n"));

    out.push_str(
        "    /// Encode (XCDR1) into `buf`, returning the total byte count.\n\
         \x20   pub fn to_cdr(&self, buf: &mut [u8], endian: Endian) -> Result<usize, CdrError> {\n\
         \x20       let mut w = Writer::new(buf, endian)?;\n\
         \x20       self.serialize_into(&mut w)?;\n\
         \x20       Ok(w.finish())\n\
         \x20   }\n\n",
    );

    out.push_str(
        "    /// Encode (PLAIN_CDR2 / XCDR2) into `buf`, returning the total byte count.\n\
         \x20   pub fn to_cdr_xcdr2(&self, buf: &mut [u8], endian: Endian) -> Result<usize, CdrError> {\n\
         \x20       let mut w = Writer::with_encoding(buf, endian, Encoding::Xcdr2)?;\n\
         \x20       self.serialize_into(&mut w)?;\n\
         \x20       Ok(w.finish())\n\
         \x20   }\n\n",
    );

    let w_param = if msg.fields.is_empty() { "_w" } else { "w" };
    out.push_str(&format!(
        "    pub fn serialize_into(&self, {w_param}: &mut Writer) -> Result<(), CdrError> {{\n"
    ));
    for f in &msg.fields {
        out.push_str(&ser_field(f));
    }
    out.push_str("        Ok(())\n    }\n\n");

    out.push_str(
        "    pub fn from_cdr(buf: &[u8]) -> Result<Self, CdrError> {\n\
         \x20       let mut r = Reader::new(buf)?;\n\
         \x20       Self::deserialize_from(&mut r)\n\
         \x20   }\n\n",
    );

    let r_param = if msg.fields.is_empty() { "_r" } else { "r" };
    out.push_str(&format!(
        "    pub fn deserialize_from({r_param}: &mut Reader) -> Result<Self, CdrError> {{\n"
    ));
    out.push_str("        Ok(Self {\n");
    for f in &msg.fields {
        out.push_str(&format!(
            "            {}: {},\n",
            field_ident(&f.name),
            de_field(f, caps)
        ));
    }
    out.push_str("        })\n    }\n");

    out.push_str("}\n");
}

// ---- serialize ----------------------------------------------------------

fn ser_field(f: &ResolvedField) -> String {
    let name = field_ident(&f.name);
    match &f.ty {
        ResolvedType::Scalar(e) => format!("        {}\n", ser_scalar(e, &name)),
        ResolvedType::Array { elem, .. } => format!(
            "        for __e in &self.{name} {{ {} }}\n",
            ser_elem_ref(elem)
        ),
        ResolvedType::Sequence { elem, .. } => format!(
            "        w.write_seq_len(self.{name}.len())?;\n        for __e in self.{name}.as_slice() {{ {} }}\n",
            ser_elem_ref(elem)
        ),
    }
}

/// Serialize a scalar field accessed as `self.<name>`.
fn ser_scalar(e: &Element, name: &str) -> String {
    match e {
        Element::Prim(p) => format!("w.write_{}(self.{name})?;", p.cdr_fn()),
        Element::String { .. } => format!("w.write_string(self.{name}.as_str())?;"),
        Element::Message(_) => format!("self.{name}.serialize_into(w)?;"),
    }
}

/// Serialize an element referenced by the loop variable `__e`.
fn ser_elem_ref(e: &Element) -> String {
    match e {
        Element::Prim(p) => format!("w.write_{}(*__e)?;", p.cdr_fn()),
        Element::String { .. } => "w.write_string(__e.as_str())?;".to_string(),
        Element::Message(_) => "__e.serialize_into(w)?;".to_string(),
    }
}

// ---- deserialize --------------------------------------------------------

fn de_field(f: &ResolvedField, caps: Caps) -> String {
    match &f.ty {
        ResolvedType::Scalar(e) => de_elem(e),
        ResolvedType::Array { elem, len } => format!(
            "{{ let mut __a = [(); {len}].map(|()| {}); for __s in &mut __a {{ *__s = {}; }} __a }}",
            elem_default(elem, caps),
            de_elem(elem)
        ),
        ResolvedType::Sequence { elem, .. } => format!(
            "{{ let __n = r.read_seq_len()?; let mut __v = BoundedVec::new(); \
             for _ in 0..__n {{ __v.push({})?; }} __v }}",
            de_elem(elem)
        ),
    }
}

/// Read one element value (propagates errors with `?`).
fn de_elem(e: &Element) -> String {
    match e {
        Element::Prim(p) => format!("r.read_{}()?", p.cdr_fn()),
        Element::String { .. } => "BoundedString::try_from_str(r.read_str()?)?".to_string(),
        Element::Message(id) => format!("{}::deserialize_from(r)?", symbol(id)),
    }
}

// ---- shared -------------------------------------------------------------

fn render_type(ty: &ResolvedType, caps: Caps) -> String {
    match ty {
        ResolvedType::Scalar(e) => render_element(e, caps),
        ResolvedType::Array { elem, len } => format!("[{}; {}]", render_element(elem, caps), len),
        ResolvedType::Sequence { elem, bound } => format!(
            "BoundedVec<{}, {}>",
            render_element(elem, caps),
            bound.unwrap_or(caps.seq)
        ),
    }
}

fn render_element(e: &Element, caps: Caps) -> String {
    match e {
        Element::Prim(p) => p.rust().to_string(),
        Element::String { bound, .. } => {
            format!("BoundedString<{}>", bound.unwrap_or(caps.string))
        }
        Element::Message(id) => symbol(id),
    }
}
