from typing import Awaitable, Callable, Iterator, Optional, Sequence, Union

from ._types import Message, MessageType

class QosProfile:
    reliability: str
    durability: str
    depth: int
    keep_all: bool
    deadline_ms: int
    lifespan_ms: int
    def __init__(
        self,
        reliability: str = ...,
        durability: str = ...,
        depth: int = ...,
        keep_all: bool = ...,
        deadline_ms: int = ...,
        lifespan_ms: int = ...,
    ) -> None: ...
    @classmethod
    def preset(cls, name: str) -> QosProfile: ...

class RoscmpError(Exception): ...
class QosError(RoscmpError): ...
class RoscmpTimeout(RoscmpError, TimeoutError): ...
class StaleHandleError(RoscmpError): ...
class WrongKindError(RoscmpError): ...
class TypeMismatchError(RoscmpError): ...
class QosIncompatibleWarning(UserWarning): ...

Handler = Callable[[Message], Union[Message, Awaitable[Message]]]

class Publisher:
    type: MessageType
    def publish(self, msg: Message) -> None: ...
    def new(self) -> Message: ...
    def close(self) -> None: ...

class Subscriber:
    type: MessageType
    def take(self) -> Optional[Message]: ...
    def messages(self, timeout: float = ...) -> Iterator[Message]: ...
    def __aiter__(self) -> Subscriber: ...
    async def __anext__(self) -> Message: ...
    def __enter__(self) -> Subscriber: ...
    def __exit__(self, *exc: object) -> None: ...
    async def __aenter__(self) -> Subscriber: ...
    async def __aexit__(self, *exc: object) -> None: ...
    def close(self) -> None: ...

class Client:
    request_type: MessageType
    response_type: MessageType
    def new_request(self) -> Message: ...
    def call_sync(self, req: Message, timeout: float = ...) -> Message: ...
    async def call(self, req: Message, timeout: float = ...) -> Message: ...
    def close(self) -> None: ...

class Service:
    request_type: MessageType
    response_type: MessageType
    def new_response(self) -> Message: ...
    def close(self) -> None: ...

class Node:
    name: str
    namespace: str
    def __init__(self, name: str, domain: int = ..., namespace: str = ...) -> None: ...
    def load_type(self, path: object, deps: Sequence[object] = ...) -> MessageType: ...
    def load_service(
        self, path: object, deps: Sequence[object] = ...
    ) -> tuple[MessageType, MessageType]: ...
    def publisher(
        self, topic: str, mtype: MessageType, qos: Optional[QosProfile] = ...
    ) -> Publisher: ...
    def subscribe(
        self, topic: str, mtype: MessageType, qos: Optional[QosProfile] = ...
    ) -> Subscriber: ...
    def client(self, name: str, req_t: MessageType, resp_t: MessageType) -> Client: ...
    def serve(
        self,
        name: str,
        srv_types: tuple[MessageType, MessageType],
        handler: Handler,
    ) -> Service: ...
    def graph(self, listen_ms: int = ...) -> dict: ...
    def close(self) -> None: ...
    def __enter__(self) -> Node: ...
    def __exit__(self, *exc: object) -> None: ...
