"""Generate ``.pyi`` stubs for dynamic message types.

All type introspection comes from the Rust layout JSON (``rcm_type_layout_json``
— the same metadata :mod:`roscmp._types` consumes at runtime); this module is
pure text formatting of that JSON into ``.pyi`` syntax. One stub module is
emitted per ROS package (``<out>/<pkg>.pyi``), containing a class per message in
the requested types' dependency closures, so IDEs autocomplete message fields
and mypy sees real types.

Field mapping mirrors runtime behaviour (:mod:`roscmp._types`):

* primitive scalars -> ``bool`` / ``int`` / ``float``
* strings -> ``str``
* primitive arrays/sequences -> ``numpy.ndarray | list[<elem>]``
* string arrays/sequences -> ``list[str]``
* nested messages -> the generated class (cross-package via module import)

Usage::

    python -m roscmp.stubgen sensor_msgs/msg/Imu -o typings
    python -m roscmp.stubgen std_msgs --type-path ./my_ws/src -o typings
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Sequence

from . import _interfaces
from ._ffi import RoscmpError, check_handle, lib, take_json

_HEADER = "# Generated by `python -m roscmp.stubgen`. Do not edit.\n"

_PRIM_PY = {
    "bool": "bool",
    "f32": "float",
    "f64": "float",
}
# Every other primitive kind (u8/i8/../u64/i64) reads as int at runtime.


def _prim_py(prim: str) -> str:
    return _PRIM_PY.get(prim, "int")


def _split_mid(mid: str) -> tuple[str, str]:
    """Split a layout message id ``pkg/Name`` into ``(pkg, Name)``."""
    pkg, _, name = mid.partition("/")
    return pkg, name


def _field_annotation(field: dict, pkg: str) -> str:
    """The ``.pyi`` annotation for one layout field, as seen from ``pkg``."""
    el = field["element"]
    kind = el["kind"]
    if kind == "prim":
        elem = _prim_py(el["prim"])
    elif kind == "string":
        elem = "str"
    else:
        ref_pkg, ref_name = _split_mid(el["message"])
        elem = ref_name if ref_pkg == pkg else f"{ref_pkg}.{ref_name}"
    if field["multiplicity"] == "scalar":
        return elem
    if kind == "prim":
        return f"numpy.ndarray | list[{elem}]"
    return f"list[{elem}]"


def _layout_for(reference: str, roots: Sequence[str]) -> dict:
    """The Rust closure-layout JSON for a ``pkg/msg/Name`` reference."""
    arr, n = _paths(roots)
    handle = lib.rcm_type_resolve(reference.encode(), arr, n)
    check_handle(handle, f"stubgen: resolve {reference}")
    try:
        return json.loads(take_json(lib.rcm_type_layout_json(handle)))
    finally:
        lib.rcm_type_free(handle)


def _paths(items: Sequence[str]):
    from ctypes import c_char_p

    encoded = [str(p).encode() for p in items]
    if not encoded:
        return None, 0
    return (c_char_p * len(encoded))(*encoded), len(encoded)


def _expand_package(pkg: str, roots: Sequence[str]) -> List[str]:
    """All ``pkg/msg/Name`` references found for ``pkg`` under the roots."""
    refs: list[str] = []
    for root in roots:
        for msg_dir in (Path(root) / pkg / "msg", Path(root) / "share" / pkg / "msg"):
            if msg_dir.is_dir():
                refs += [f"{pkg}/msg/{p.stem}" for p in sorted(msg_dir.glob("*.msg"))]
    if not refs:
        raise RoscmpError(f"stubgen: no .msg files found for package '{pkg}'")
    return sorted(set(refs))


def collect_layouts(
    references: Sequence[str], type_paths: Sequence[str] = ()
) -> Dict[str, Dict[str, dict]]:
    """Resolve references (``pkg/msg/Name`` or bare ``pkg``) into per-package
    message layouts: ``{pkg: {Name: layout}}`` over every dependency closure.
    """
    roots = _interfaces.search_roots(list(type_paths))
    refs: list[str] = []
    for ref in references:
        if "/" in ref:
            refs.append(ref)
        else:
            refs += _expand_package(ref, roots)
    packages: Dict[str, Dict[str, dict]] = {}
    for ref in refs:
        layout = _layout_for(ref, roots)
        for mid, message in layout["messages"].items():
            pkg, name = _split_mid(mid)
            packages.setdefault(pkg, {})[name] = message
    return packages


def render_package(pkg: str, messages: Dict[str, dict]) -> str:
    """Format one package's message classes as ``.pyi`` text."""
    imports = set()
    uses_numpy = False
    bodies: list[str] = []
    for name in sorted(messages):
        fields = messages[name]["fields"]
        lines = [f"class {name}:"]
        if not fields:
            lines.append("    ...")
        for f in fields:
            ann = _field_annotation(f, pkg)
            if "numpy." in ann:
                uses_numpy = True
            for other in _referenced_packages(f, pkg):
                imports.add(other)
            lines.append(f"    {f['name']}: {ann}")
        bodies.append("\n".join(lines))
    out = [_HEADER]
    if uses_numpy:
        out.append("import numpy\n")
    out += [f"import {other}\n" for other in sorted(imports)]
    out.append("\n")
    out.append("\n\n".join(bodies))
    out.append("\n")
    return "".join(out)


def _referenced_packages(field: dict, pkg: str) -> List[str]:
    el = field["element"]
    if el["kind"] != "message":
        return []
    ref_pkg, _ = _split_mid(el["message"])
    return [] if ref_pkg == pkg else [ref_pkg]


def generate(
    references: Sequence[str],
    out_dir: str | Path,
    type_paths: Sequence[str] = (),
) -> List[Path]:
    """Write ``<out_dir>/<pkg>.pyi`` for every package in the closures of
    ``references``. Returns the written paths.
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for pkg, messages in sorted(collect_layouts(references, type_paths).items()):
        path = out / f"{pkg}.pyi"
        path.write_text(render_package(pkg, messages))
        written.append(path)
    return written


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m roscmp.stubgen",
        description="Generate .pyi stubs for ROS message types from the Rust "
        "layout metadata.",
    )
    parser.add_argument(
        "references",
        nargs="+",
        help="type references (pkg/msg/Name) or bare package names",
    )
    parser.add_argument("-o", "--out", default="typings", help="output directory")
    parser.add_argument(
        "--type-path",
        action="append",
        default=[],
        help="extra interface search root (repeatable)",
    )
    args = parser.parse_args(argv)
    for path in generate(args.references, args.out, args.type_path):
        print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
