from typing import (
    AsyncIterator,
    Awaitable,
    Callable,
    Iterator,
    List,
    Optional,
    Sequence,
    Tuple,
    Union,
)

from ._types import Message, MessageType

ParamValue = Union[bool, int, float, str, bytes, bytearray, list, tuple]

GOAL_STATUS_SUCCEEDED: int
GOAL_STATUS_CANCELED: int
GOAL_STATUS_ABORTED: int

class QosProfile:
    reliability: str
    durability: str
    depth: int
    keep_all: bool
    deadline_ms: int
    lifespan_ms: int
    def __init__(
        self,
        reliability: str = ...,
        durability: str = ...,
        depth: int = ...,
        keep_all: bool = ...,
        deadline_ms: int = ...,
        lifespan_ms: int = ...,
    ) -> None: ...
    @classmethod
    def preset(cls, name: str) -> QosProfile: ...

class RoswellError(Exception): ...
class QosError(RoswellError): ...
class RoswellTimeout(RoswellError, TimeoutError): ...
class StaleHandleError(RoswellError): ...
class WrongKindError(RoswellError): ...
class TypeMismatchError(RoswellError): ...
class QosIncompatibleWarning(UserWarning): ...

Handler = Callable[[Message], Union[Message, Awaitable[Message]]]

class Publisher:
    type: MessageType
    topic: str
    def publish(self, msg: Message) -> None: ...
    def new(self) -> Message: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...

class Subscriber:
    type: MessageType
    topic: str
    def take(self) -> Optional[Message]: ...
    def messages(self, timeout: float = ...) -> Iterator[Message]: ...
    def __aiter__(self) -> Subscriber: ...
    async def __anext__(self) -> Message: ...
    def __enter__(self) -> Subscriber: ...
    def __exit__(self, *exc: object) -> None: ...
    async def __aenter__(self) -> Subscriber: ...
    async def __aexit__(self, *exc: object) -> None: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...

class Client:
    request_type: MessageType
    response_type: MessageType
    name: str
    def new_request(self) -> Message: ...
    def call_sync(self, req: Message, timeout: float = ...) -> Message: ...
    async def call(self, req: Message, timeout: float = ...) -> Message: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...

class Service:
    request_type: MessageType
    response_type: MessageType
    name: str
    def new_response(self) -> Message: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...

class Feedback:
    goal_id: bytes
    message: Message
    def __init__(self, goal_id: bytes, message: Message) -> None: ...

class ActionTypes:
    action_type: str
    goal: MessageType
    result: MessageType
    feedback: MessageType
    send_goal_request: MessageType
    send_goal_response: MessageType
    get_result_request: MessageType
    get_result_response: MessageType
    feedback_message: MessageType
    def __init__(self, node: Node, action_type: object) -> None: ...
    def __repr__(self) -> str: ...

class ActionClient:
    name: str
    action_type: str
    goal_type: MessageType
    result_type: MessageType
    feedback_type: MessageType
    def new_goal(self) -> Message: ...
    def server_is_ready(self) -> bool: ...
    def wait_for_server(self, timeout: float = ...) -> bool: ...
    def send_goal_sync(self, goal: Message, timeout: float = ...) -> Tuple[bytes, bool]: ...
    async def send_goal(self, goal: Message, timeout: float = ...) -> Tuple[bytes, bool]: ...
    def get_result_sync(self, goal_id: bytes, timeout: float = ...) -> Tuple[int, Message]: ...
    async def get_result(self, goal_id: bytes, timeout: float = ...) -> Tuple[int, Message]: ...
    def poll_feedback(self) -> Optional[Feedback]: ...
    def feedback(self, timeout: float = ...) -> Iterator[Feedback]: ...
    def feedback_async(self, timeout: float = ...) -> AsyncIterator[Feedback]: ...
    def cancel_sync(self, goal_id: Optional[bytes] = ..., timeout: float = ...) -> int: ...
    async def cancel(self, goal_id: Optional[bytes] = ..., timeout: float = ...) -> int: ...
    def __enter__(self) -> ActionClient: ...
    def __exit__(self, *exc: object) -> None: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...

class Transform:
    translation: Tuple[float, float, float]
    rotation: Tuple[float, float, float, float]
    def __init__(
        self,
        translation: Tuple[float, float, float],
        rotation: Tuple[float, float, float, float],
    ) -> None: ...

class TfBuffer:
    def lookup_transform(
        self, target: str, source: str, time: Optional[float] = ...
    ) -> Transform: ...
    def can_transform(
        self, target: str, source: str, time: Optional[float] = ...
    ) -> bool: ...
    def broadcast(
        self,
        parent: str,
        child: str,
        transform: Transform,
        time: Optional[float] = ...,
        static: bool = ...,
    ) -> None: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...

class ServerGoalHandle:
    goal_id: bytes
    def new_feedback(self) -> Message: ...
    def new_result(self) -> Message: ...
    def publish_feedback(self, msg: Message) -> None: ...
    @property
    def is_cancel_requested(self) -> bool: ...
    def __repr__(self) -> str: ...

ExecuteCallback = Callable[
    [Message, ServerGoalHandle], Union[Message, Awaitable[Message]]
]

class ActionServer:
    name: str
    action_type: str
    goal_type: MessageType
    result_type: MessageType
    feedback_type: MessageType
    def new_result(self) -> Message: ...
    def __enter__(self) -> ActionServer: ...
    def __exit__(self, *exc: object) -> None: ...
    def close(self) -> None: ...
    def __repr__(self) -> str: ...

class Timer:
    period: float
    def __init__(
        self, period: float, callback: Callable[[], Union[None, Awaitable[None]]]
    ) -> None: ...
    def cancel(self) -> None: ...
    def __repr__(self) -> str: ...

class Node:
    name: str
    namespace: str
    def __init__(
        self,
        name: str,
        domain: int = ...,
        namespace: str = ...,
        type_paths: Sequence[object] = ...,
    ) -> None: ...
    def load_type(self, path: object, deps: Sequence[object] = ...) -> MessageType: ...
    def load_service(
        self, path: object, deps: Sequence[object] = ...
    ) -> tuple[MessageType, MessageType]: ...
    def load_action(self, action_type: object) -> ActionTypes: ...
    def action_client(self, action_name: str, action_type: object) -> ActionClient: ...
    def action_server(
        self,
        action_name: str,
        action_type: object,
        execute_callback: ExecuteCallback,
        cancel_callback: Optional[Callable[[ServerGoalHandle], None]] = ...,
    ) -> ActionServer: ...
    def tf_buffer(self) -> TfBuffer: ...
    def publisher(
        self, topic: str, mtype: MessageType, qos: Optional[QosProfile] = ...
    ) -> Publisher: ...
    def subscribe(
        self, topic: str, mtype: MessageType, qos: Optional[QosProfile] = ...
    ) -> Subscriber: ...
    def client(self, name: str, req_t: MessageType, resp_t: MessageType) -> Client: ...
    def serve(
        self,
        name: str,
        srv_types: tuple[MessageType, MessageType],
        handler: Handler,
    ) -> Service: ...
    def graph(self, listen_ms: int = ...) -> dict: ...
    def declare_parameter(self, name: str, value: ParamValue) -> ParamValue: ...
    def set_parameter(self, name: str, value: ParamValue) -> None: ...
    def get_parameter(self, name: str) -> ParamValue: ...
    def list_parameters(self) -> List[str]: ...
    def create_timer(
        self, period: float, callback: Callable[[], Union[None, Awaitable[None]]]
    ) -> Timer: ...
    def close(self) -> None: ...
    def __enter__(self) -> Node: ...
    def __exit__(self, *exc: object) -> None: ...
    def __repr__(self) -> str: ...
