// Generated by roscmp. Do not edit.
#![allow(
    non_camel_case_types,
    non_upper_case_globals,
    dead_code,
    clippy::all,
    clippy::pedantic,
    clippy::nursery
)]
use core::ffi::c_char;

// CDR (Classic CDR / XCDR1) runtime. This file is `include!`d by `src/cdr.rs`
// for in-crate unit tests, and embedded verbatim into generated bindings so
// they are self-contained. Keep it free of inner attributes (`//!`) and of
// anything that depends on the rest of the crate.

/// CDR representation identifier (first 2 bytes of the encapsulation header).
const REPR_CDR_BE: [u8; 2] = [0x00, 0x00];
const REPR_CDR_LE: [u8; 2] = [0x00, 0x01];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Endian {
    Little,
    Big,
}

impl Endian {
    /// The native endianness of the host.
    pub const NATIVE: Endian = if cfg!(target_endian = "little") {
        Endian::Little
    } else {
        Endian::Big
    };
}

/// Tracks the alignment origin so padding is computed relative to the body, not
/// the raw buffer (the encapsulation header sits before the origin).
#[derive(Debug, Clone, Copy)]
struct Cursor {
    origin: usize,
}

impl Cursor {
    /// Bytes needed to align `pos` to `a` relative to the body origin.
    fn padding(self, pos: usize, a: usize) -> usize {
        let off = pos - self.origin;
        (a - (off % a)) % a
    }
}

/// Serializes values into a CDR byte buffer.
#[derive(Debug)]
pub struct Writer {
    buf: Vec<u8>,
    endian: Endian,
    cursor: Cursor,
}

impl Writer {
    /// Start a new message, emitting the encapsulation header.
    pub fn new(endian: Endian) -> Self {
        let mut buf = Vec::with_capacity(64);
        buf.extend_from_slice(match endian {
            Endian::Little => &REPR_CDR_LE,
            Endian::Big => &REPR_CDR_BE,
        });
        buf.extend_from_slice(&[0x00, 0x00]); // options
        let origin = buf.len();
        Writer {
            buf,
            endian,
            cursor: Cursor { origin },
        }
    }

    /// Consume the writer and return the full message (header + body).
    pub fn finish(self) -> Vec<u8> {
        self.buf
    }

    fn align(&mut self, a: usize) {
        let pad = self.cursor.padding(self.buf.len(), a);
        self.buf.resize(self.buf.len() + pad, 0);
    }

    fn put(&mut self, le: &[u8], be: &[u8]) {
        match self.endian {
            Endian::Little => self.buf.extend_from_slice(le),
            Endian::Big => self.buf.extend_from_slice(be),
        }
    }

    pub fn write_u8(&mut self, v: u8) {
        self.buf.push(v);
    }
    pub fn write_i8(&mut self, v: i8) {
        self.buf.push(v as u8);
    }
    pub fn write_bool(&mut self, v: bool) {
        self.buf.push(u8::from(v));
    }

    pub fn write_u16(&mut self, v: u16) {
        self.align(2);
        self.put(&v.to_le_bytes(), &v.to_be_bytes());
    }
    pub fn write_i16(&mut self, v: i16) {
        self.write_u16(v as u16);
    }

    pub fn write_u32(&mut self, v: u32) {
        self.align(4);
        self.put(&v.to_le_bytes(), &v.to_be_bytes());
    }
    pub fn write_i32(&mut self, v: i32) {
        self.write_u32(v as u32);
    }
    pub fn write_f32(&mut self, v: f32) {
        self.write_u32(v.to_bits());
    }

    pub fn write_u64(&mut self, v: u64) {
        self.align(8);
        self.put(&v.to_le_bytes(), &v.to_be_bytes());
    }
    pub fn write_i64(&mut self, v: i64) {
        self.write_u64(v as u64);
    }
    pub fn write_f64(&mut self, v: f64) {
        self.write_u64(v.to_bits());
    }

    /// Write a `string`: `uint32` length incl. NUL, bytes, then NUL.
    pub fn write_string(&mut self, s: &str) {
        let bytes = s.as_bytes();
        self.write_u32((bytes.len() + 1) as u32);
        self.buf.extend_from_slice(bytes);
        self.buf.push(0);
    }

    /// Write a sequence length prefix (`uint32` element count).
    pub fn write_seq_len(&mut self, n: usize) {
        self.write_u32(n as u32);
    }
}

/// Error reading a CDR buffer.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CdrError {
    Truncated,
    BadEncapsulation,
    BadUtf8,
    BadString,
}

impl std::fmt::Display for CdrError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            CdrError::Truncated => "unexpected end of CDR buffer",
            CdrError::BadEncapsulation => "invalid CDR encapsulation header",
            CdrError::BadUtf8 => "string is not valid UTF-8",
            CdrError::BadString => "string is missing its NUL terminator",
        };
        f.write_str(s)
    }
}

impl std::error::Error for CdrError {}

/// Deserializes values from a CDR byte buffer.
#[derive(Debug)]
pub struct Reader<'a> {
    buf: &'a [u8],
    pos: usize,
    endian: Endian,
    cursor: Cursor,
}

impl<'a> Reader<'a> {
    /// Parse the encapsulation header and position at the body start.
    pub fn new(buf: &'a [u8]) -> Result<Self, CdrError> {
        if buf.len() < 4 {
            return Err(CdrError::BadEncapsulation);
        }
        let endian = match [buf[0], buf[1]] {
            REPR_CDR_LE => Endian::Little,
            REPR_CDR_BE => Endian::Big,
            _ => return Err(CdrError::BadEncapsulation),
        };
        Ok(Reader {
            buf,
            pos: 4,
            endian,
            cursor: Cursor { origin: 4 },
        })
    }

    pub fn endian(&self) -> Endian {
        self.endian
    }

    fn align(&mut self, a: usize) {
        self.pos += self.cursor.padding(self.pos, a);
    }

    fn take(&mut self, n: usize) -> Result<&'a [u8], CdrError> {
        let end = self.pos.checked_add(n).ok_or(CdrError::Truncated)?;
        let slice = self.buf.get(self.pos..end).ok_or(CdrError::Truncated)?;
        self.pos = end;
        Ok(slice)
    }

    fn get<const N: usize>(&mut self, a: usize) -> Result<[u8; N], CdrError> {
        self.align(a);
        let slice = self.take(N)?;
        let mut arr = [0u8; N];
        arr.copy_from_slice(slice);
        Ok(arr)
    }

    fn decode_u16(&self, b: [u8; 2]) -> u16 {
        match self.endian {
            Endian::Little => u16::from_le_bytes(b),
            Endian::Big => u16::from_be_bytes(b),
        }
    }
    fn decode_u32(&self, b: [u8; 4]) -> u32 {
        match self.endian {
            Endian::Little => u32::from_le_bytes(b),
            Endian::Big => u32::from_be_bytes(b),
        }
    }
    fn decode_u64(&self, b: [u8; 8]) -> u64 {
        match self.endian {
            Endian::Little => u64::from_le_bytes(b),
            Endian::Big => u64::from_be_bytes(b),
        }
    }

    pub fn read_u8(&mut self) -> Result<u8, CdrError> {
        Ok(self.take(1)?[0])
    }
    pub fn read_i8(&mut self) -> Result<i8, CdrError> {
        Ok(self.read_u8()? as i8)
    }
    pub fn read_bool(&mut self) -> Result<bool, CdrError> {
        Ok(self.read_u8()? != 0)
    }

    pub fn read_u16(&mut self) -> Result<u16, CdrError> {
        let b = self.get::<2>(2)?;
        Ok(self.decode_u16(b))
    }
    pub fn read_i16(&mut self) -> Result<i16, CdrError> {
        Ok(self.read_u16()? as i16)
    }

    pub fn read_u32(&mut self) -> Result<u32, CdrError> {
        let b = self.get::<4>(4)?;
        Ok(self.decode_u32(b))
    }
    pub fn read_i32(&mut self) -> Result<i32, CdrError> {
        Ok(self.read_u32()? as i32)
    }
    pub fn read_f32(&mut self) -> Result<f32, CdrError> {
        Ok(f32::from_bits(self.read_u32()?))
    }

    pub fn read_u64(&mut self) -> Result<u64, CdrError> {
        let b = self.get::<8>(8)?;
        Ok(self.decode_u64(b))
    }
    pub fn read_i64(&mut self) -> Result<i64, CdrError> {
        Ok(self.read_u64()? as i64)
    }
    pub fn read_f64(&mut self) -> Result<f64, CdrError> {
        Ok(f64::from_bits(self.read_u64()?))
    }

    /// Read a `string` (length incl. NUL, bytes, NUL).
    pub fn read_string(&mut self) -> Result<String, CdrError> {
        let len = self.read_u32()? as usize;
        if len == 0 {
            return Err(CdrError::BadString);
        }
        let bytes = self.take(len)?;
        if bytes[len - 1] != 0 {
            return Err(CdrError::BadString);
        }
        std::str::from_utf8(&bytes[..len - 1])
            .map(str::to_string)
            .map_err(|_| CdrError::BadUtf8)
    }

    /// Read a sequence length prefix (`uint32` element count).
    pub fn read_seq_len(&mut self) -> Result<usize, CdrError> {
        Ok(self.read_u32()? as usize)
    }
}

/// ABI of a ROS string: NUL-terminated, owning pointer + length + capacity.
#[repr(C)]
pub struct RosString {
    pub data: *mut c_char,
    pub size: usize,
    pub capacity: usize,
}

impl RosString {
    /// # Safety
    /// `data` must point to `size` valid UTF-8 bytes.
    pub unsafe fn as_str(&self) -> &str {
        if self.data.is_null() || self.size == 0 {
            return "";
        }
        let bytes = core::slice::from_raw_parts(self.data as *const u8, self.size);
        core::str::from_utf8_unchecked(bytes)
    }

    /// Allocate an owning, NUL-terminated copy of `s`.
    pub fn alloc(s: &str) -> Self {
        let mut bytes = s.as_bytes().to_vec();
        bytes.push(0);
        let mut bytes = core::mem::ManuallyDrop::new(bytes);
        RosString {
            data: bytes.as_mut_ptr() as *mut c_char,
            size: bytes.len() - 1,
            capacity: bytes.capacity(),
        }
    }

    /// # Safety
    /// Frees the owned buffer; call at most once. Idempotent on null.
    pub unsafe fn free(&mut self) {
        if !self.data.is_null() {
            drop(Vec::from_raw_parts(
                self.data as *mut u8,
                self.capacity,
                self.capacity,
            ));
            self.data = core::ptr::null_mut();
            self.size = 0;
            self.capacity = 0;
        }
    }
}

/// ABI of a ROS sequence: owning pointer + length + capacity.
#[repr(C)]
pub struct RosSequence<T> {
    pub data: *mut T,
    pub size: usize,
    pub capacity: usize,
}

impl<T> RosSequence<T> {
    /// # Safety
    /// `data` must point to `size` valid `T` values.
    pub unsafe fn as_slice(&self) -> &[T] {
        if self.data.is_null() {
            return &[];
        }
        core::slice::from_raw_parts(self.data, self.size)
    }

    /// Take ownership of `v`'s buffer.
    pub fn alloc(v: Vec<T>) -> Self {
        let mut v = core::mem::ManuallyDrop::new(v);
        RosSequence {
            data: v.as_mut_ptr(),
            size: v.len(),
            capacity: v.capacity(),
        }
    }

    /// # Safety
    /// Reconstitutes the owning `Vec`; call at most once.
    pub unsafe fn into_vec(self) -> Vec<T> {
        Vec::from_raw_parts(self.data, self.size, self.capacity)
    }
}

/// Owned byte buffer returned across the FFI boundary.
#[repr(C)]
pub struct RoscmpBuf {
    pub ptr: *mut u8,
    pub len: usize,
    pub cap: usize,
}

/// Free a buffer produced by a `*_serialize` call.
#[no_mangle]
pub extern "C" fn roscmp_buf_free(buf: RoscmpBuf) {
    if !buf.ptr.is_null() {
        unsafe {
            drop(Vec::from_raw_parts(buf.ptr, buf.len, buf.cap));
        }
    }
}

/// RIHS01 type hash (matches ROS2 discovery).
pub const example_interfaces__AddTwoInts_Request__TYPE_HASH: &str =
    "RIHS01_53b483262b7b7e728d3f6a75779ec8118a320f1c86fe9cdeb204aa709505bd72";
#[repr(C)]
pub struct example_interfaces__AddTwoInts_Request {
    pub a: i64,
    pub b: i64,
}

impl example_interfaces__AddTwoInts_Request {
    pub fn to_cdr(&self, endian: Endian) -> Vec<u8> {
        let mut w = Writer::new(endian);
        unsafe {
            self.serialize_into(&mut w);
        }
        w.finish()
    }

    /// # Safety
    /// Reads owning pointers in strings/sequences; they must be valid.
    pub unsafe fn serialize_into(&self, w: &mut Writer) {
        w.write_i64(self.a);
        w.write_i64(self.b);
    }

    pub fn from_cdr(buf: &[u8]) -> Result<Self, CdrError> {
        let mut r = Reader::new(buf)?;
        Self::deserialize_from(&mut r)
    }

    pub fn deserialize_from(r: &mut Reader) -> Result<Self, CdrError> {
        Ok(Self {
            a: r.read_i64()?,
            b: r.read_i64()?,
        })
    }

    /// # Safety
    /// Frees owned buffers; call at most once per owned message.
    pub unsafe fn fini(&mut self) {}
}

#[no_mangle]
pub extern "C" fn roscmp_example_interfaces__AddTwoInts_Request_serialize(
    msg: *const example_interfaces__AddTwoInts_Request,
    endian: u8,
) -> RoscmpBuf {
    if msg.is_null() {
        return RoscmpBuf {
            ptr: core::ptr::null_mut(),
            len: 0,
            cap: 0,
        };
    }
    let e = if endian == 0 {
        Endian::Little
    } else {
        Endian::Big
    };
    let v = unsafe { (*msg).to_cdr(e) };
    let mut v = core::mem::ManuallyDrop::new(v);
    RoscmpBuf {
        ptr: v.as_mut_ptr(),
        len: v.len(),
        cap: v.capacity(),
    }
}

#[no_mangle]
pub extern "C" fn roscmp_example_interfaces__AddTwoInts_Request_deserialize(
    buf: *const u8,
    len: usize,
    out: *mut example_interfaces__AddTwoInts_Request,
) -> i32 {
    if buf.is_null() || out.is_null() {
        return -1;
    }
    let slice = unsafe { core::slice::from_raw_parts(buf, len) };
    match example_interfaces__AddTwoInts_Request::from_cdr(slice) {
        Ok(m) => {
            unsafe {
                core::ptr::write(out, m);
            }
            0
        }
        Err(_) => -1,
    }
}

#[no_mangle]
pub extern "C" fn roscmp_example_interfaces__AddTwoInts_Request_fini(
    msg: *mut example_interfaces__AddTwoInts_Request,
) {
    if !msg.is_null() {
        unsafe {
            (*msg).fini();
        }
    }
}

/// RIHS01 type hash (matches ROS2 discovery).
pub const example_interfaces__AddTwoInts_Response__TYPE_HASH: &str =
    "RIHS01_7bb1b9225d00538f5479e368ad03f3a38e30c473b31c1c4ee8255a1744ec8b36";
#[repr(C)]
pub struct example_interfaces__AddTwoInts_Response {
    pub sum: i64,
}

impl example_interfaces__AddTwoInts_Response {
    pub fn to_cdr(&self, endian: Endian) -> Vec<u8> {
        let mut w = Writer::new(endian);
        unsafe {
            self.serialize_into(&mut w);
        }
        w.finish()
    }

    /// # Safety
    /// Reads owning pointers in strings/sequences; they must be valid.
    pub unsafe fn serialize_into(&self, w: &mut Writer) {
        w.write_i64(self.sum);
    }

    pub fn from_cdr(buf: &[u8]) -> Result<Self, CdrError> {
        let mut r = Reader::new(buf)?;
        Self::deserialize_from(&mut r)
    }

    pub fn deserialize_from(r: &mut Reader) -> Result<Self, CdrError> {
        Ok(Self { sum: r.read_i64()? })
    }

    /// # Safety
    /// Frees owned buffers; call at most once per owned message.
    pub unsafe fn fini(&mut self) {}
}

#[no_mangle]
pub extern "C" fn roscmp_example_interfaces__AddTwoInts_Response_serialize(
    msg: *const example_interfaces__AddTwoInts_Response,
    endian: u8,
) -> RoscmpBuf {
    if msg.is_null() {
        return RoscmpBuf {
            ptr: core::ptr::null_mut(),
            len: 0,
            cap: 0,
        };
    }
    let e = if endian == 0 {
        Endian::Little
    } else {
        Endian::Big
    };
    let v = unsafe { (*msg).to_cdr(e) };
    let mut v = core::mem::ManuallyDrop::new(v);
    RoscmpBuf {
        ptr: v.as_mut_ptr(),
        len: v.len(),
        cap: v.capacity(),
    }
}

#[no_mangle]
pub extern "C" fn roscmp_example_interfaces__AddTwoInts_Response_deserialize(
    buf: *const u8,
    len: usize,
    out: *mut example_interfaces__AddTwoInts_Response,
) -> i32 {
    if buf.is_null() || out.is_null() {
        return -1;
    }
    let slice = unsafe { core::slice::from_raw_parts(buf, len) };
    match example_interfaces__AddTwoInts_Response::from_cdr(slice) {
        Ok(m) => {
            unsafe {
                core::ptr::write(out, m);
            }
            0
        }
        Err(_) => -1,
    }
}

#[no_mangle]
pub extern "C" fn roscmp_example_interfaces__AddTwoInts_Response_fini(
    msg: *mut example_interfaces__AddTwoInts_Response,
) {
    if !msg.is_null() {
        unsafe {
            (*msg).fini();
        }
    }
}

/// RIHS01 type hash (matches ROS2 discovery).
pub const geometry_msgs__Vector3__TYPE_HASH: &str =
    "RIHS01_cc12fe83e4c02719f1ce8070bfd14aecd40f75a96696a67a2a1f37f7dbb0765d";
#[repr(C)]
pub struct geometry_msgs__Vector3 {
    pub x: f64,
    pub y: f64,
    pub z: f64,
}

impl geometry_msgs__Vector3 {
    pub fn to_cdr(&self, endian: Endian) -> Vec<u8> {
        let mut w = Writer::new(endian);
        unsafe {
            self.serialize_into(&mut w);
        }
        w.finish()
    }

    /// # Safety
    /// Reads owning pointers in strings/sequences; they must be valid.
    pub unsafe fn serialize_into(&self, w: &mut Writer) {
        w.write_f64(self.x);
        w.write_f64(self.y);
        w.write_f64(self.z);
    }

    pub fn from_cdr(buf: &[u8]) -> Result<Self, CdrError> {
        let mut r = Reader::new(buf)?;
        Self::deserialize_from(&mut r)
    }

    pub fn deserialize_from(r: &mut Reader) -> Result<Self, CdrError> {
        Ok(Self {
            x: r.read_f64()?,
            y: r.read_f64()?,
            z: r.read_f64()?,
        })
    }

    /// # Safety
    /// Frees owned buffers; call at most once per owned message.
    pub unsafe fn fini(&mut self) {}
}

#[no_mangle]
pub extern "C" fn roscmp_geometry_msgs__Vector3_serialize(
    msg: *const geometry_msgs__Vector3,
    endian: u8,
) -> RoscmpBuf {
    if msg.is_null() {
        return RoscmpBuf {
            ptr: core::ptr::null_mut(),
            len: 0,
            cap: 0,
        };
    }
    let e = if endian == 0 {
        Endian::Little
    } else {
        Endian::Big
    };
    let v = unsafe { (*msg).to_cdr(e) };
    let mut v = core::mem::ManuallyDrop::new(v);
    RoscmpBuf {
        ptr: v.as_mut_ptr(),
        len: v.len(),
        cap: v.capacity(),
    }
}

#[no_mangle]
pub extern "C" fn roscmp_geometry_msgs__Vector3_deserialize(
    buf: *const u8,
    len: usize,
    out: *mut geometry_msgs__Vector3,
) -> i32 {
    if buf.is_null() || out.is_null() {
        return -1;
    }
    let slice = unsafe { core::slice::from_raw_parts(buf, len) };
    match geometry_msgs__Vector3::from_cdr(slice) {
        Ok(m) => {
            unsafe {
                core::ptr::write(out, m);
            }
            0
        }
        Err(_) => -1,
    }
}

#[no_mangle]
pub extern "C" fn roscmp_geometry_msgs__Vector3_fini(msg: *mut geometry_msgs__Vector3) {
    if !msg.is_null() {
        unsafe {
            (*msg).fini();
        }
    }
}

/// RIHS01 type hash (matches ROS2 discovery).
pub const geometry_msgs__Twist__TYPE_HASH: &str =
    "RIHS01_9c45bf16fe0983d80e3cfe750d6835843d265a9a6c46bd2e609fcddde6fb8d2a";
#[repr(C)]
pub struct geometry_msgs__Twist {
    pub linear: geometry_msgs__Vector3,
    pub angular: geometry_msgs__Vector3,
}

impl geometry_msgs__Twist {
    pub fn to_cdr(&self, endian: Endian) -> Vec<u8> {
        let mut w = Writer::new(endian);
        unsafe {
            self.serialize_into(&mut w);
        }
        w.finish()
    }

    /// # Safety
    /// Reads owning pointers in strings/sequences; they must be valid.
    pub unsafe fn serialize_into(&self, w: &mut Writer) {
        self.linear.serialize_into(w);
        self.angular.serialize_into(w);
    }

    pub fn from_cdr(buf: &[u8]) -> Result<Self, CdrError> {
        let mut r = Reader::new(buf)?;
        Self::deserialize_from(&mut r)
    }

    pub fn deserialize_from(r: &mut Reader) -> Result<Self, CdrError> {
        Ok(Self {
            linear: geometry_msgs__Vector3::deserialize_from(r)?,
            angular: geometry_msgs__Vector3::deserialize_from(r)?,
        })
    }

    /// # Safety
    /// Frees owned buffers; call at most once per owned message.
    pub unsafe fn fini(&mut self) {
        self.linear.fini();
        self.angular.fini();
    }
}

#[no_mangle]
pub extern "C" fn roscmp_geometry_msgs__Twist_serialize(
    msg: *const geometry_msgs__Twist,
    endian: u8,
) -> RoscmpBuf {
    if msg.is_null() {
        return RoscmpBuf {
            ptr: core::ptr::null_mut(),
            len: 0,
            cap: 0,
        };
    }
    let e = if endian == 0 {
        Endian::Little
    } else {
        Endian::Big
    };
    let v = unsafe { (*msg).to_cdr(e) };
    let mut v = core::mem::ManuallyDrop::new(v);
    RoscmpBuf {
        ptr: v.as_mut_ptr(),
        len: v.len(),
        cap: v.capacity(),
    }
}

#[no_mangle]
pub extern "C" fn roscmp_geometry_msgs__Twist_deserialize(
    buf: *const u8,
    len: usize,
    out: *mut geometry_msgs__Twist,
) -> i32 {
    if buf.is_null() || out.is_null() {
        return -1;
    }
    let slice = unsafe { core::slice::from_raw_parts(buf, len) };
    match geometry_msgs__Twist::from_cdr(slice) {
        Ok(m) => {
            unsafe {
                core::ptr::write(out, m);
            }
            0
        }
        Err(_) => -1,
    }
}

#[no_mangle]
pub extern "C" fn roscmp_geometry_msgs__Twist_fini(msg: *mut geometry_msgs__Twist) {
    if !msg.is_null() {
        unsafe {
            (*msg).fini();
        }
    }
}

/// RIHS01 type hash (matches ROS2 discovery).
pub const std_msgs__String__TYPE_HASH: &str =
    "RIHS01_df668c740482bbd48fb39d76a70dfd4bd59db1288021743503259e948f6b1a18";
#[repr(C)]
pub struct std_msgs__String {
    pub data: RosString,
}

impl std_msgs__String {
    pub fn to_cdr(&self, endian: Endian) -> Vec<u8> {
        let mut w = Writer::new(endian);
        unsafe {
            self.serialize_into(&mut w);
        }
        w.finish()
    }

    /// # Safety
    /// Reads owning pointers in strings/sequences; they must be valid.
    pub unsafe fn serialize_into(&self, w: &mut Writer) {
        w.write_string(self.data.as_str());
    }

    pub fn from_cdr(buf: &[u8]) -> Result<Self, CdrError> {
        let mut r = Reader::new(buf)?;
        Self::deserialize_from(&mut r)
    }

    pub fn deserialize_from(r: &mut Reader) -> Result<Self, CdrError> {
        Ok(Self {
            data: RosString::alloc(&r.read_string()?),
        })
    }

    /// # Safety
    /// Frees owned buffers; call at most once per owned message.
    pub unsafe fn fini(&mut self) {
        self.data.free();
    }
}

#[no_mangle]
pub extern "C" fn roscmp_std_msgs__String_serialize(
    msg: *const std_msgs__String,
    endian: u8,
) -> RoscmpBuf {
    if msg.is_null() {
        return RoscmpBuf {
            ptr: core::ptr::null_mut(),
            len: 0,
            cap: 0,
        };
    }
    let e = if endian == 0 {
        Endian::Little
    } else {
        Endian::Big
    };
    let v = unsafe { (*msg).to_cdr(e) };
    let mut v = core::mem::ManuallyDrop::new(v);
    RoscmpBuf {
        ptr: v.as_mut_ptr(),
        len: v.len(),
        cap: v.capacity(),
    }
}

#[no_mangle]
pub extern "C" fn roscmp_std_msgs__String_deserialize(
    buf: *const u8,
    len: usize,
    out: *mut std_msgs__String,
) -> i32 {
    if buf.is_null() || out.is_null() {
        return -1;
    }
    let slice = unsafe { core::slice::from_raw_parts(buf, len) };
    match std_msgs__String::from_cdr(slice) {
        Ok(m) => {
            unsafe {
                core::ptr::write(out, m);
            }
            0
        }
        Err(_) => -1,
    }
}

#[no_mangle]
pub extern "C" fn roscmp_std_msgs__String_fini(msg: *mut std_msgs__String) {
    if !msg.is_null() {
        unsafe {
            (*msg).fini();
        }
    }
}

/// RIHS01 type hash (matches ROS2 discovery).
pub const turtlesim__Pose__TYPE_HASH: &str =
    "RIHS01_739beba26bcba6920404ba722b7b8321348512f92ea5be235c47251940dd8aa9";
#[repr(C)]
pub struct turtlesim__Pose {
    pub x: f32,
    pub y: f32,
    pub theta: f32,
    pub linear_velocity: f32,
    pub angular_velocity: f32,
}

impl turtlesim__Pose {
    pub fn to_cdr(&self, endian: Endian) -> Vec<u8> {
        let mut w = Writer::new(endian);
        unsafe {
            self.serialize_into(&mut w);
        }
        w.finish()
    }

    /// # Safety
    /// Reads owning pointers in strings/sequences; they must be valid.
    pub unsafe fn serialize_into(&self, w: &mut Writer) {
        w.write_f32(self.x);
        w.write_f32(self.y);
        w.write_f32(self.theta);
        w.write_f32(self.linear_velocity);
        w.write_f32(self.angular_velocity);
    }

    pub fn from_cdr(buf: &[u8]) -> Result<Self, CdrError> {
        let mut r = Reader::new(buf)?;
        Self::deserialize_from(&mut r)
    }

    pub fn deserialize_from(r: &mut Reader) -> Result<Self, CdrError> {
        Ok(Self {
            x: r.read_f32()?,
            y: r.read_f32()?,
            theta: r.read_f32()?,
            linear_velocity: r.read_f32()?,
            angular_velocity: r.read_f32()?,
        })
    }

    /// # Safety
    /// Frees owned buffers; call at most once per owned message.
    pub unsafe fn fini(&mut self) {}
}

#[no_mangle]
pub extern "C" fn roscmp_turtlesim__Pose_serialize(
    msg: *const turtlesim__Pose,
    endian: u8,
) -> RoscmpBuf {
    if msg.is_null() {
        return RoscmpBuf {
            ptr: core::ptr::null_mut(),
            len: 0,
            cap: 0,
        };
    }
    let e = if endian == 0 {
        Endian::Little
    } else {
        Endian::Big
    };
    let v = unsafe { (*msg).to_cdr(e) };
    let mut v = core::mem::ManuallyDrop::new(v);
    RoscmpBuf {
        ptr: v.as_mut_ptr(),
        len: v.len(),
        cap: v.capacity(),
    }
}

#[no_mangle]
pub extern "C" fn roscmp_turtlesim__Pose_deserialize(
    buf: *const u8,
    len: usize,
    out: *mut turtlesim__Pose,
) -> i32 {
    if buf.is_null() || out.is_null() {
        return -1;
    }
    let slice = unsafe { core::slice::from_raw_parts(buf, len) };
    match turtlesim__Pose::from_cdr(slice) {
        Ok(m) => {
            unsafe {
                core::ptr::write(out, m);
            }
            0
        }
        Err(_) => -1,
    }
}

#[no_mangle]
pub extern "C" fn roscmp_turtlesim__Pose_fini(msg: *mut turtlesim__Pose) {
    if !msg.is_null() {
        unsafe {
            (*msg).fini();
        }
    }
}
